# -*- coding: utf-8 -*-
"""calc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13bXH36m1kBxjpUs1Y8NYnK3QI7QfLzYz
"""

import sys

def is_number(value):
    try:
        float(value)
        return True
    except ValueError:
        return False

# 명령줄 인수에서 숫자 가져오기
if len(sys.argv) != 3:
    print("사용법: python calc.py <숫자1> <숫자2>")
    sys.exit(1)

if not (is_number(sys.argv[1]) and is_number(sys.argv[2])):
    print("모든 인수는 숫자여야 합니다.")
    sys.exit(1)

# 인수를 숫자로 변환
num1 = float(sys.argv[1])
num2 = float(sys.argv[2])

# 사칙연산 수행
plus = num1 + num2
minus = num1 - num2
mul = num1 * num2
div = num1 / num2 if num2 != 0 else "무한대 (0으로 나눌 수 없습니다)"

# 결과값 출력
print(f"{num1} + {num2} = {plus}")
print(f"{num1} - {num2} = {minus}")
print(f"{num1} * {num2} = {mul}")
print(f"{num1} / {num2} = {div}")
